### ISSUE TITLE
files.riichi.moe for retards

### ISSUE THREAD

**Issue by sharmayu** [vg-mjg/mjg-repo#140]
wtf i can't download everything in one click.
\>noooo you're supposed to KNOW what to do
\>you HAVE to select them all, and then press download
\>lmao imagine using a gui just command line a 400 character line of code to download everything
just let me download the whole emote pack in one click PLEASE

**Comment by chinponya** [comment]
This is why anywhere on the repo we link to multiple files, there's also a zip link, so you don't have to do that.
![image](https://user-images.githubusercontent.com/58706956/170994190-e93bf1b1-1ee6-4614-bb04-d36c5b1f9b1e.png)
Note that this site isn't supposed to replace the repo. We should be using it more or less like catbox/mega - as a dumb storage. What happens on that site is just an extra feature or quirk.
I'd argue that in this case being able to selectively download certain emotes is better for both uploaders and people updating their local copies of the pack, since they don't need to upload/download everything every time, but that's beside the point.

**Comment by sharmayu** [comment]
I didn't know that zip link was a separate link from the text link... i'll make it more distinct

**Comment by sharmayu** [comment]
aaand done.
