### ISSUE TITLE
pathofhouou/osamuko backups

### ISSUE THREAD

**Issue by watterle** [vg-mjg/mjg-repo#75]
There was some talk yesterday about making copies of the articles on these sites https://pathofhouou.blogspot.com/ and (added myself) https://osamuko.com/.
This last one actually did die some years ago and it hasn't been updated for a while, so there might be a reason for making a backup. Any of you know how to do it without too much work?

**Comment by Furitenman** [comment]
One of the osamuko's authors seemed to have moved his stuff to: https://npmahjong.com/ and seems pretty active. Might be worth to actually look through and filter, since many of the things are news, and collect their most useful articles, then make a backup. Can't hurt to contact the guy and maybe get a DB dump?

**Comment by watterle** [comment]
if it's just 2 pages I can simply copy paste them, hitori page done

**Comment by sharmayu** [comment]
and the programs themselves
